### ISSUE TITLE
Credentials Header not allowed

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-react-components#111]
The credentials header is not in `Access-Control-Allow-Headers`.

To replicate, log into https://develop.generator.inrupt.com and upload a new profile photo:

This will make an options request that includes the header `Access-Control-Request-Headers: authorization,content-type,credentials` The server returns the header `Access-Control-Allow-Headers: Authorization, Accept, Content-Type, Origin, Referer, X-Requested-With, Link, Slug`

Because this does not contain `credentials`, the following error is thrown

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://otherjackson.api.swype.io/profile/_1564002195000_.jpeg. (Reason: CORS request did not succeed).
```

**Comment by james-martin-jd** [comment]
@jaxoncreed I am unable to replicate this error - when I log into develop and use my pod and upload a profile photo, it succeeds without any error or console messages. There is also no credentials header:

`Access-Control-Request-Headers: authorization,content-type`

Can you provide more details about how you were able to generate this error and header?
