### ISSUE TITLE
Better example of how to use ProviderLogin

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-react-components#115]
For instance [`callbackUri={`${window.location.origin}/welcome`}`](https://github.com/inrupt/generator-solid-react/blob/develop/generators/app/templates/src/containers/Login/login.component.js#L38) seems to be required? Also there's a typo ['inputPlaholder'](https://github.com/inrupt/solid-react-components#providerlogin)

**Comment by james-martin-jd** [comment]
Good catch - the callbackUri is used to pass into solid-auth-client (so we know where to go on-return). The docs can be updated to reflect this.

**Comment by james-martin-jd** [comment]
Issues have been fixed and will be included in the next release.
