### ISSUE TITLE
Error logging in with WebId-OIDC

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-react-components#116]
I'm trying to use the ProviderLogin component, but sometimes see this:

<img width="893" alt="Screenshot 2019-09-24 12 02 26" src="https://user-images.githubusercontent.com/408412/65502526-42125f00-dec3-11e9-8c74-a6aed030119a.png">

Will try to find out some more information about this.

**Comment by michielbdejong** [comment]
I should be able to bisect this against https://generator.inrupt.com/welcome# because that seems to be using this same component but not have this problem.

**Comment by james-martin-jd** [comment]
Thanks Michiel. We've found some issues logging in in general that may be related - some similar login problems that result in an error on the provider similarly require a cleared storage. I'm wondering if there's some issues in the login functionality - sometimes errors actually show on the provider page when typing username/password when switching users (something to the tune of "User is logged in as 2" or thereabouts). 

Regardless, we aren't handling the error well, and could probably provide some instructions, especially with the new solidsdk pod we're using for in-depth troubleshooting instructions.

**Comment by james-martin-jd** [comment]
@michielbdejong I tested this with an IPS login and immediately saw the error you saw. Without even refreshing the page, I used an NSS5 account (inrupt.net) and it succeeded. I suspect this is a server issue.

**Comment by michielbdejong** [comment]
Yeah, it might be triggered by server behaviour, but if the only work-around is to clear localStorage then we need to do better handling the error on the client side.

Can we at least try to find out where the 'invalid type' message comes from, and clear localStorage when solid-auth-client encounters it?

**Comment by james-martin-jd** [comment]
I suppose that's one way to tackle it, yeah. I wonder if something in solid-auth-client (or rather, that library's localStorage object) is getting corrupted somehow? Clearing the localStorage is really just treating the symptom and not the cause.
