### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-react-components#137]
it seems that when you check out this repo and run `npm install`, there are a number of errors like:
```sh
npm WARN tar ENOENT: no such file or directory, open '/Users/michiel/gh/inrupt/solid-react-components/node_modules/.staging/...
```

With `yarn install` it works better, but still seeing this one:
```sh
error An unexpected error occurred: "https://registry.npmjs.org/solid-forms: Not found".
```

**Comment by michielbdejong** [comment]
Fixed in ^

**Comment by james-martin-jd** [comment]
This should be fixed in the develop branch now, we published the as-of-then unpublished solid-forms repo as @inrupt/solid-sdk-forms in a dev tag and will use that moving forward instead of relying on private npm repos that break external builds.
