### ISSUE TITLE
https://localhost:8443/profile/card#me should be allowed as a webid

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-react-components#143]
When you run node-solid-server in single-user mode, your webid is https://localhost:8443/profile/card#me - the ProviderLogin component should consider that a valid webid.

**Comment by james-martin-jd** [comment]
After reviewing this, it looks like the RegEx that's being used is not allowing localhost URLs. Will review the RegEx.

**Comment by james-martin-jd** [comment]
The regex has been updated for use with localhost and a few other configurations. If you'd like to try it out, it's been released on the dev tag (`npm install .--save solid-react-components@dev`)
