### ISSUE TITLE
Please review bundle size

### ISSUE THREAD

**Issue by jairo-campos-JD** [inrupt/solid-react-components#15]

**Comment by mrkvon** [comment]
Thank you for your effort on this.

I'm building a [solid react app](https://git.mrkvon.org/livegraph/solid-math), and the bundle has 3.4 M, out of which [almost 85 %](https://bundlephobia.com/scan-results?packages=@inrupt/solid-react-components@0.4.4,@solid/query-ldflex@2.6.0,@solid/react@1.4.0,axios@0.18.0,d3-drag@1.2.4,d3-force@2.0.0,d3-selection@1.4.0,graphlib@2.1.7,rdflib@0.19.1,react@16.8.3,react-dom@16.8.3,react-mathjax-preview@0.1.16,react-redux@6.0.1,react-router-dom@5.1.2,react-select@2.4.1,redux@4.0.1,redux-orm@0.14.1,redux-orm-proptypes@0.1.0,redux-thunk@2.3.0,reselect@4.0.0,styled-components@4.3.2) is @inrupt/solid-react-components, @solid/query-ldflex, @solid/react and rdflib. And [the application](https://math.livegraph.org) just took me 30 seconds to load with suboptimal internet connection. The first-time users will likely be discouraged by this. (On subsequent loads the bundle is cached, so things are fast...)

Why are these packages so large? Can they be further reduced, or split so we can use only the needed parts?

I believe a long loading time can be a single point of failure of solid react apps using these packages.
