### ISSUE TITLE
Weird type statement in code

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/solid-react-components#171]
We found the following code (`constants/index.js`):

```javascript
export const ACL_PREFIXES = {
  acl: 'http://www.w3.org/ns/auth/acl#',
  foaf: 'http://xmlns.com/foaf/0.1/',
  n: 'http://www.w3.org/2006/vcard/ns#',
  a: 'http://www.w3.org/ns/auth/acl#type'
};
```

which is used as follows (`access-control-list.js`):

```javascript
    const { acl, foaf, a } = ACL_PREFIXES;
    const subject = `${this.aclUri}#${modes.join('')}`;
    const { documentUri } = this;
    const originalPredicates = [
      this.createQuad(subject, `${a}`, namedNode(`${acl}Authorization`)),
      this.createQuad(subject, `${acl}accessTo`, namedNode(documentUri)),
      this.createQuad(subject, `${acl}default`, namedNode(documentUri))
    ];
```

However, the symbol `a` in Turtle points to `rdf:type` or `http://www.w3.org/1999/02/22-rdf-syntax-ns#type`, not to `http://www.w3.org/ns/auth/acl#type`.

So the code is creating bogus triples

```turtle
<> <http://www.w3.org/ns/auth/acl#type> <http://www.w3.org/ns/auth/acl#Authorization>.
```

The reason it works is because the ACL checker does not _need_ a type statement. But if we add one, we probably want to do it right 🙂

**Comment by james-martin-jd** [comment]
Nice catch! This will likely be in the 0.7.1 generator release / 0.5.1 components release, unless we patch it into the current release candidate. Would you consider this a patchable type of issue?

**Comment by RubenVerborgh** [comment]
Seems patchable, but not urgent. It's just a lost triple at the moment, nothing breaks.

**Comment by james-martin-jd** [comment]
Just merged the PR over to the release branch so it will be in the patch release for `0.7.0-rc.1`
