### ISSUE TITLE
Needs error handling when trying to use WebID on a server that is offline

### ISSUE THREAD

**Issue by megoth** [inrupt/solid-react-components#30]
![image](https://user-images.githubusercontent.com/775139/52787777-31615700-305f-11e9-8b2e-5438e25fe124.png)

I've been using https://dev-generator.inrupt.com to test out functionality, and now that my local server is offline, it fails badly.

We should implement better error handling for these scenarios (albeit rare, they will happen).

**Comment by michielbdejong** [comment]
Triaged for when?

**Comment by Eliamar** [comment]
The fix was deployed here: https://develop.generator.inrupt.com - this url: https://dev-generator.inrupt.com is now deprecated. The spinner is no longer present on each screen change and a toastr notification is being displayed for error handling.

**Comment by michielbdejong** [comment]
@Eliamar you are right that now the spinner is no longer shown, but I think the complaint was not about the presence of a spinner, but rather that no feedback like "invalid webid" is shown.

Now when I click 'log in' with an invalid webid, the error is only logged to the console, not shown to the user:

<img width="1426" alt="Screenshot 2019-11-10 16 23 14" src="https://user-images.githubusercontent.com/408412/68546494-00883580-03d7-11ea-8653-9c08071e9c6c.png">

cc @james-martin-jd

**Comment by michielbdejong** [comment]
This seems related to https://github.com/inrupt/solid-react-components/blob/develop/src/lib/components/ProviderLogin/provider-login.container.js#L75 maybe? I'm trying to debug this locally but having some trouble setting up my dev env for this repo, due to https://github.com/inrupt/solid-react-components/issues/137

**Comment by michielbdejong** [comment]
Fixing this in #142

**Comment by michielbdejong** [comment]
@megoth apparently this was already fixed but not deployed yet, but James just deployed to develop and I think this issue can be closed now, can you try now on https://develop.generator.inrupt.com/ ?

**Comment by kevin-howard-jd** [comment]
If a user attempts to log into the SDK (https://develop.generator.inrupt.com) while the server is offline, a generic `Something is wrong, please try again...` message is displayed as the SDK cannot know exactly what happens. 
<img width="642" alt="SomethingWentWrong" src="https://user-images.githubusercontent.com/45850928/68792809-218c9880-061a-11ea-91c2-b9d4c10ece53.png">

This update will be included in the next release.

**Comment by james-martin-jd** [comment]
@michielbdejong Also, to add to this, as a rule we're not closing issues until they are resolved on master. Develop branch is great, but can be unstable as we develop new things. It is a dev branch after all!

Once the develop branch is merged with master it is deployed to https://generator.inrupt.com which we consider to be our "prod" server.
