### ISSUE TITLE
Add a script to install external dependencies

### ISSUE THREAD

**Issue by mrkvon** [inrupt/solid-react-components#38]
Manual researching and installing all the external dependencies is time- and energy-consuming. It would be very useful to have a copy-paste command in README for yarn and npm.

**Comment by james-martin-jd** [comment]
Thank you for the issue, and sorry for the late reply. For the solid-react-component library, all the items listed in External Dependencies are there only for reference purposes, and are installed as part of the npm process. Simply running `npm install` will install all those modules and they are in the package.json file already. I will update the documentation to clarify.
