### ISSUE TITLE
allow https://localhost:8443/profile/card#me as a webid

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-react-components#56]
When running node-solid-server locally, your webid has localhost:8443 as the host and does not pass the  regex which requires a TLD.

(funny workaround: type in https://lolcathost.de:8443/profile/card#me as your  WebID)

**Comment by james-martin-jd** [comment]
Moved to the components repository because this is where the logic for this issue is

**Comment by james-martin-jd** [comment]
An updated version of the regex has been released, which should allow localhost
